### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Ritiek** [telegram-rs/telegram-bot#76]
Thanks for working on this but I am facing an issue.

I tried to compile [simple.rs](https://github.com/telegram-rs/telegram-bot/blob/master/lib/examples/simple.rs) with my token but it gives me

>Compiling telegram_test v0.1.0 (file:///home/pi/scripts/rust/telegram_test)
>error[E0433]: failed to resolve. Use of undeclared type or module `UpdateKind`
>--> src/main.rs:21:16
>      |
>21  |         if let UpdateKind::Message(message) = update.kind {
>      |                ^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `UpdateKind`
>error[E0433]: failed to resolve. Use of undeclared type or module `MessageKind`
>  --> src/main.rs:29:20
>     |
>29 |             if let MessageKind::Text {ref data, ..} = message.kind {
>     |                    ^^^^^^^^^^^^^^^^^ Use of undeclared type or module `MessageKind`
>error: no associated item named `configure` found for type `telegram_bot::Api` in the current scope
>  --> src/main.rs:15:15
>      |
>15  |     let api = Api::configure(token).build(core.handle());
>      |               ^^^^^^^^^^^^^^
>error: aborting due to previous error
>error: Could not compile `telegram_test`.
>To learn more, run the command again with --verbose.

My dependencies section in `Cargo.toml`

```
[dependencies]
futures = "0.1.13"
telegram-bot = "0.5"
tokio-core = "0.1.7"
```
Output of `cargo -V`
>cargo 0.18.0 (fe7b0cdcf 2017-04-24)

Output of `rustc -V`
>rustc 1.17.0 (56124baa9 2017-04-24)

Output of `uname -a`
>Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

Am I missing something?

**Comment by knsd** [comment]
Hi!

This library is completely rewritten since 0.5 release (tokio and a lot of api changes), and this example is only works with develop version. 

New release is scheduled for June. You [can use](http://doc.crates.io/specifying-dependencies.html#specifying-dependencies-from-git-repositories) development version, but I can't guarantee that no future change will break public api somehow.

[Stable version examples](https://github.com/telegram-rs/telegram-bot/tree/60408e3ccef0f9d35d83273415e5356647ffb9f9/examples)

**Comment by Ritiek** [comment]
okay, thanks! :+1:
